on:
  push:
    branches:
      - new3
      - main
  workflow_dispatch:
    branches:
      - main
      - new3
    inputs:
      git-tag:
        description: 'Branch/hash/tag'
        required: true
        default: 'main'
